# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mainText', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTitle', models.CharField(max_length=50)),
                ('imageURL', models.CharField(max_length=50)),
            ],
        ),
    ]
